# Generated by Django 4.1.3 on 2023-02-18 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='Text Area')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Project Date')),
                ('image', models.ImageField(default=None, upload_to='projects', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Text Area')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(verbose_name='Text Area')),
            ],
        ),
    ]
