# Generated by Django 4.1.3 on 2023-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Image'),
        ),
    ]
