# Generated by Django 4.1.3 on 2023-04-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buisness_card', '0006_project_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsanswer',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
